### PR TITLE
Replace node and terraform with nvm and tfenv respectively

### PR DESCRIPTION
**Pull request by lukaf**
nvm and tfenv allow quick and easy Node.js and terraform version
swiching commonly required when working on different projects.

Additional changes requires:
- remove version from kubectl installation as the repository only has
the latest one
- set installation method of ansible to pip which respects the version attribute

### CODE REVIEW

**Review by jf-delineate — CHANGES_REQUESTED** [review]
Hey, thanks for looking at this!  

There are a few points it would be good to consider/refine....

For `kubectl` it looks like there is a new version available in the repo.  As we've locked the other packages to explicit version (to avoid version drift) we should do probably do the same.  Running `apt-cache policy kubectl` there looks to be a new version 1.20.2-00.

On the installs are there any package options?  If not, are there options to install through Ansible tasks rather than custom scripts?  The implementation in `provision.yml` prefers native tasks over custom tasks, examples of how some of the steps maybe accomplished.   

For instance `git clone` can be accomplished using…
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html

Symlink can be created through the file 
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html

I didn't fully understand the need to set the $PATH on the npm task?  WOuld be good to understand other options.   

Lastly in terms of maintaining state or setting versions by project we may want to add a script that runs from the bash profile that sets versions based on env variables through the .env file that is sourced.  This will make this configurable per project.

**Comment by lukaf** [comment]
> For `kubectl` it looks like there is a new version available in the repo. As we've locked the other packages to explicit version (to avoid version drift) we should do probably do the same. Running `apt-cache policy kubectl` there looks to be a new version 1.20.2-00.

Absolutely, however there's only one version available which means drift is not possible and it would need to be updated on regular basis - well, at least when building the box.

But explicit is better than implicit, so keeping a version is better than having to understand the logic behind availability of a single version.

> On the installs are there any package options? If not, are there options to install through Ansible tasks rather than custom scripts? The implementation in `provision.yml` prefers native tasks over custom tasks, examples of how some of the steps maybe accomplished...
> 
> `git clone`…
> https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
> 
> `ln`...
> https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html

Sadly none of them come as packages.
I've done it this way as I didn't find it much different to the way the other "Shell installs" are done, except that these two require additional steps and I found it clearer when all were put together under a single `shell` run compared to multiple steps.

However, I fully agree using modules would be a much better way. The steps could be compiled in a role or block, whichever is preferred - I'm leaning towards blocks as these are already used in the playbook and less complex than roles. What do you think?

> I didn't fully understand the need to set the $PATH on the npm task? Would be good to understand other options (if any)?

The `nvm` tool works by manipulating the `PATH` environment variable which only works when user logs in and during the process the `bash_profile` is sourced. When Ansible runs the `npm` module it doesn't source those files and `nvm` has no effect, so modifying `PATH` environment variable for this task is effectively mimicking what `nvm` does.

Another option was to use `executable` parameter of the `npm` [module](https://docs.ansible.com/ansible/latest/collections/community/general/npm_module.html#parameter-executable), but `npm` is just a script that depends on `node` executable and it's not possible to use the `executable` parameter to define both.
 
> Lastly in terms of setting the versions might want to consider using the .env to set versions and sleecting by start up scripts. This will make this more configurable per project.

This would be great! I wasn't aware of this option and will need to do some tests to become more familiar with it and come up with something useful.

**Comment by jf-delineate** [comment]
Thanks @lukaf!

## Blocks vs Modules

I think blocks make more sense for consistency but also to reduce external dependencies at this point. Certainly the blocks are potential candidates for roles in the future once the dev reaches stability.  

## .env

In `provision.yml` currently an empty file (as per below) is added and then sourced in the `.bash_profile`.

```yaml
   - name: Create empty .env file
     file:
       path: ~/.env
       state: touch
       modification_time: preserve
       access_time: preserve
     become_user: vagrant
```

Projects can overwrite `~/.env` and add project specific env variables.   This enables scripts from `./ansible/scripts` when `.bash_profile` is sourced to take advantage of provided env variables

A good example of this is `kube.sh` that looks for `$GOOGLE_CLUSTER_NAME` and if provided automatically configures `kubectl` to connect to the cluster.  

I tried to explain this in the [readme](https://github.com/delineateio/box#copying-files-to-vm).

## To Note

I have been thinking about how to improve the ability to run config steps when an ssh connect is established rather than running custom shell scripts.  I have created an issue to change this approach to actually use a ansible playbook when connecting via ssh.  [Issue 11](https://github.com/delineateio/box/issues/11).

**Comment by lukaf** [comment]
Updated the code to use modules instead of the script and accepts optional environment variables to install specific versions of terraform and Node.js.

**Review by jf-delineate — DISMISSED** [review]
Thanks @lukaf.  In parallel I had been looking at installing `gvm` which is a golang equivalent of `nvm` and the changes are basically identify so that is good!

**Comment by jf-delineate** [comment]
Ah @lukaf there is a technicality blocking accepting the PR!  I have changed the repo to only accept signed commits because I'm using the project as a reference for good practice :)

Please can you have a a look at the documentation (see below) on how to configure this and then sign update the PR with a signed commit.  

https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification

**Comment by lukaf** [comment]
> Ah @lukaf there is a technicality blocking accepting the PR! I have changed the repo to only accept signed commits because I'm using the project as a reference for good practice :)
> 
> Please can you have a a look at the documentation (see below) on how to configure this and then sign update the PR with a signed commit.
> 
> https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification

Will do.
I had to create a new commit as I forgot to remove two tasks I used to debug. Sorry.

**Review by jf-delineate — DISMISSED** [review]

**Comment by lukaf** [comment]
Is signing just the last commit enough or should I redo the whole PR?
Thanks!

**Comment by jf-delineate** [comment]
@lukaf I'd recommend doing a rebase on the 4 commits and then the new consolidated commit will be signed. I always find it a bit easier to review when there the is a single commit.

**Pull request closed without merging**
